### ISSUE TITLE
Allow uiEndpoint and openapi endpoint to be optional

### ISSUE THREAD

**Issue by rozenraymond** [atlassian/koa-oas3#13]
Is it possible to make the swagger ui (/openapi.html) and endpoint to display the openapi schema (/openapi.json) to be optional? 

For security reason, I would much prefer to have the swagger ui and also the endpoint showing the whole openapi schema to be available only in development environment. 

Thanks!

**Comment by supertong** [comment]
Valid point. I have added `enableUi` config to the latest release.
