### ISSUE TITLE
Make possible to disable logging

### ISSUE THREAD

**Issue by VolodymyrMachekhin** [atlassian/koa-oas3#153]
Hello team, 
I tried to search for the answer here but couldn't find the solution. 
Is there a way to remove the following logs at the initialization without forking the library:
```
strict mode: unknown keyword: "example"
```
here is the code that produces them
``` javascript
const middleware = await oas({
    file: options.specFilePath,
    enableUi: false,
    validateResponse: options.validateResponse ?? true,
    errorHandler: (err, ctx) => {
      (ctx.openApiValidationErrorActions as ErrorAction[]).push(() => {
        options.errorCallback?.(err, ctx);
      });
    },
  });
```
Thanks in advance 🙇

**Comment by supertong** [comment]
Hey @VolodymyrMachekhin , the warning is from `ajv` strict mode. You can find more details here. https://ajv.js.org/strict-mode.html

I would recommend to fix your schema instead but if you really want to disable it, you can overwrite the default `ajv` options by using the `validationOptions`.

**Comment by VolodymyrMachekhin** [comment]
Thank you @supertong, I added "example" to keywords and it uncovered true issues that were hidden in the logs.
