### ISSUE TITLE
OAS URL in UI is incorrect

### ISSUE THREAD

**Issue by gregbacchus** [atlassian/koa-oas3#21]
When opening the OpenAPI UI, the URL that it tries to load is incorrect. It's just the URL of the UI page with the URL of the OAS JSON on the end, e.g. `/openapi.html/openapi.json`

To correctly resolve the relative URL:

https://github.com/atlassian/koa-oas3/blob/0c69c457a18fd0f14470290405b6e89a34d30680/src/openapi-ui.ts#L84

should be `url: new URL(cfg.url, window.location.href).href,`

**Comment by RusTit** [comment]
@gregbacchus @supertong 
If no regressions were is detected, this may be closed.
