### ISSUE TITLE
Depending on `oas-validator` via GitHub prevents installations in secure environments

### ISSUE THREAD

**Issue by andrewhughson** [atlassian/koa-oas3#49]
In my work environment (and I'm sure others) there is a security/operational requirement that all third party NPM packages are installed from a local mirror.

The change in #43 to depend on `oas-validator` from a GitHub URL prevents this package being mirrored and installation fails.

As a workaround for now, I'm pinning the dependency version to `1.0.1` (the version before this was introduced).

I'm creating this issue mainly to raise awareness that this may be causing problems, and to keep track of when the dependency can be installed normally again.

**Comment by supertong** [comment]
Thanks @andrewhughson , the reason we introduce that change was for a security fix. I will install it normally as soon as the fix is available in `oas-validator` itself.

**Comment by supertong** [comment]
@psychowico @andrewhughson Feel free to leave your ideas on it, otherwise I will merge it in next few days.
https://github.com/atlassian/koa-oas3/pull/52

**Comment by MikeRalphson** [comment]
`oas-validator@5.0.0` has been released which resolves this security vulnerability.

**Comment by mtth** [comment]
Hi @supertong - would you be open to a PR which bumps `oas-validator` to `5.0.x`? It sounds like it addresses the vulnerability and this issue.

**Comment by supertong** [comment]
`oas-validator` is bumped in latest release.

**Comment by mtth** [comment]
Nice - thanks!
