### ISSUE TITLE
path params not set correctly in ctx.oas.request

### ISSUE THREAD

**Issue by crizo23** [atlassian/koa-oas3#93]
I believe there is a bug here: https://github.com/atlassian/koa-oas3/blob/master/src/index.ts#L56
This line does a logical and (&&), returning the value of the second operand if the first is truthy. I don't believe `path.params` is set anywhere by the validator in `oas3-chow-chow`, so it ends up being undefined, and therefor `ctx.oas.request.params` is always undefined. 

Tests pass without && validRequest.path.params, so I will attempt a PR if I don't hear back on this thread

**Comment by supertong** [comment]
Hey @crizo23 , I think you are right. Feel free to raise a PR for it.

**Comment by crizo23** [comment]
fixed in https://github.com/atlassian/koa-oas3/pull/94
